name: Rust Build

on:
  push:
    branches: [ dev ]

jobs:
  build:
    name: Build for ${{ matrix.os }} and ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change working directory
        run: echo "CARGO_WORKSPACE=$(pwd)/src" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        env:
          CARGO_MANIFEST_PATH: ${{ env.CARGO_WORKSPACE }}/Cargo.toml
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mjfw-version-${{ matrix.target }}
          path: src/mjfw-version/target/${{ matrix.target }}/release/mjfw-version
